// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUxCxPE1Dbs7aXoEL9p9R_M6Puhb0F73c',
    appId: '1:746712254012:web:f93b68c5779f93e6056539',
    messagingSenderId: '746712254012',
    projectId: 'accounting-arya',
    authDomain: 'accounting-arya.firebaseapp.com',
    storageBucket: 'accounting-arya.firebasestorage.app',
    measurementId: 'G-MQTB50BK4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhSc_mAbgs8lrnv4YUCsjkP90PARHRR0M',
    appId: '1:746712254012:android:c7d0c70b552ba8c6056539',
    messagingSenderId: '746712254012',
    projectId: 'accounting-arya',
    storageBucket: 'accounting-arya.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Av7Xh08Mx7PBHRqwRqKtUXPojPXEutY',
    appId: '1:746712254012:ios:04bbc2628fa0cce9056539',
    messagingSenderId: '746712254012',
    projectId: 'accounting-arya',
    storageBucket: 'accounting-arya.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );
}
